export const ALL_STOCK_REQUEST = "ALL_STOCK_REQUEST";
export const ALL_STOCK_SUCCESS = "ALL_STOCK_SUCCESS";
export const ALL_STOCK_FAIL = "ALL_STOCK_FAIL";

export const STOCK_DETAILS_REQUEST = "STOCK_DETAILS_REQUEST";
export const STOCK_DETAILS_SUCCESS = "STOCK_DETAILS_SUCCESS";
export const STOCK_DETAILS_FAIL = "STOCK_DETAILS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
