export const TRANSFER_STOCK_REQUEST = "TRANSFER_STOCK_REQUEST";
export const TRANSFER_STOCK_SUCCESS = "TRANSFER_STOCK_SUCCESS";
export const TRANSFER_STOCK_FAIL = "TRANSFER_STOCK_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
